# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
destination:    ./_gh_pages
port:           9001
baseurl:        "/bootstrap-theme"
url:            "https://bcgov.github.io/bootstrap-theme"
encoding:       UTF-8
exclude:
  - .git
  - .github
  - assets/scss/
  - build
  - js
  - node_modules
  - nuget
  - scss
  - vendor
  - bower.json
  - composer.json
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package.js
  - package.json
  - package-lock.json
  - sache.json

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              B.C. Government Bootstrap Theme
description:        "The most popular HTML, CSS, and JS library in the world themed with B.C. Government look-and-feel"
authors:            "Greg Turner"

# Custom variables
repo:               "https://github.com/bcgov/bootstrap-theme"
